#!/usr/bin/env bash
# using scp to move files from client to server
if [ $# -lt 3 ]; then
	echo "Usage: 0-transer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3"@"$2":~/
fi
