#!/usr/bin/env bash
# install nginx web server with fw requirements and default home page

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
echo "Server {
	listen 80 default_server;
	listen [::}:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
