#!/usr/bin/env bash
# install nginx web server with fw requirements and default home page

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

echo 'Server {
        listen 80 default_server;
        listen [::}:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

	error_page 404 /var/www/html/404.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}' | sudo tee /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart
