#!/usr/bin/env bash
# creates file containing it's pid. Displays text indefinitely
# Prints some text when receiving some Signals
# deletes file on some signals.

trap 'echo "I hate the kill command" && rm /var/run/myscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
