#!/usr/bin/env bash
# displays numbers 1 to 20 with 4, 9 and 17 chinese superstitions
n=1
while [ $n -le 20 ]
do
	echo "$n"
	case "$n" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	n=$((n + 1))
done
