#!/usr/bin/env bash
# fix nginx to run as nginx user not root
pkill "$(netstat -lpn | grep 8080 | awk '{print $7}' | cut -d'/' -f2)"
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill nginx
sudo -u nginx nginx
